# Generated by Django 5.1.6 on 2025-03-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ["name"],
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
            },
        ),
    ]
