# Generated by Django 5.1.6 on 2025-03-07 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_alter_category_options_alter_equipment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
