# Generated by Django 5.1.6 on 2025-03-08 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_alter_equipment_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_equipment",
                through="manager.EquipmentEmployeeAssignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
